// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcD-JGzYSF-EHvx9C45Qp5ect-LuXGtSA',
    appId: '1:377335298672:web:bf78f5e2c289c35f4b12b5',
    messagingSenderId: '377335298672',
    projectId: 'orange-card-7abba',
    authDomain: 'orange-card-7abba.firebaseapp.com',
    databaseURL: 'https://orange-card-7abba-default-rtdb.firebaseio.com',
    storageBucket: 'orange-card-7abba.appspot.com',
    measurementId: 'G-777FTHSREJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALDZDTjgcRiYel-s98Qv8WOqMZA1gCHgI',
    appId: '1:377335298672:android:0db0dc36361db2c84b12b5',
    messagingSenderId: '377335298672',
    projectId: 'orange-card-7abba',
    databaseURL: 'https://orange-card-7abba-default-rtdb.firebaseio.com',
    storageBucket: 'orange-card-7abba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEKYjr7E4DRoaoKYzc7dw1l-J4Y1dbalY',
    appId: '1:377335298672:ios:155b0657447b2dad4b12b5',
    messagingSenderId: '377335298672',
    projectId: 'orange-card-7abba',
    databaseURL: 'https://orange-card-7abba-default-rtdb.firebaseio.com',
    storageBucket: 'orange-card-7abba.appspot.com',
    iosBundleId: 'com.example.orangeCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEKYjr7E4DRoaoKYzc7dw1l-J4Y1dbalY',
    appId: '1:377335298672:ios:155b0657447b2dad4b12b5',
    messagingSenderId: '377335298672',
    projectId: 'orange-card-7abba',
    databaseURL: 'https://orange-card-7abba-default-rtdb.firebaseio.com',
    storageBucket: 'orange-card-7abba.appspot.com',
    iosBundleId: 'com.example.orangeCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcD-JGzYSF-EHvx9C45Qp5ect-LuXGtSA',
    appId: '1:377335298672:web:f4aa85b3633a9f134b12b5',
    messagingSenderId: '377335298672',
    projectId: 'orange-card-7abba',
    authDomain: 'orange-card-7abba.firebaseapp.com',
    databaseURL: 'https://orange-card-7abba-default-rtdb.firebaseio.com',
    storageBucket: 'orange-card-7abba.appspot.com',
    measurementId: 'G-ZW189KFSVG',
  );
}
